**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE: Mónica María Ramírez Mejía
*   MATRÍCULA: A01797493

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [291]:
pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)

ERROR:sqlalchemy.pool.impl.QueuePool:Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python3.12/pathlib.py", line 441, in __str__
    return self._str
           ^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/pathlib.py", line 555, in drive
    return self._drv
           ^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute '_drv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sqlalchemy/pool/base.py", line 985, in _finalize_fairy
    fairy._reset(
  File "/usr/local/lib/python3.12/dist-packages/sqlalchemy/pool/base.py", line 1433, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.12/dist-packages/sqlalchemy/engine/default.py", line 711, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.12/dist-packages/pymysql/connections.py", line 505, in rollback
    self._read_ok_packet()
  File "/usr/local/lib/python3.12/dist-packages/pymysql/connections.py", line 465, in _read_ok_packet
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymysql/connections.py", line 760, in _read_packet
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [292]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [293]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC4029User:mnaTC4029Pass!@20.51.200.131:3306/Netflix', pool_recycle=14400)
conn = db.connect()

In [294]:
pd.read_sql("SHOW TABLES;", conn)

  Tables_in_Netflix
0             movie
1            season
2           tv_show
3      view_summary

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae la información de las películas que duran más de 5 horas.

In [295]:
query = sqla.text("""
  SELECT title, runtime, (runtime/60) as 'Duracion_hrs'
  FROM movie
  WHERE (runtime/60) > 5
  ORDER BY (runtime/60) DESC;
""")
pd.read_sql(query, conn)

                                               title  runtime  Duracion_hrs
0                   Nihontouitsu Series: Film Series     3892       64.8667
1                  Free and Easy Series: Film Series     2120       35.3333
2                             Seiji Oda: Film Series      710       11.8333
3  Kingdom ~ The Man Who Became the Top ~: Film S...      427        7.1167
4                           Navarasa: Limited Series      312        5.2000

In [296]:
query = sqla.text("""
  SELECT COUNT(id)
  FROM movie;
""")
pd.read_sql(query, conn)

   COUNT(id)
0      11787

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`?

In [297]:
query = sqla.text("""
  SELECT COUNT(available_globally)
  FROM movie;
  """)
pd.read_sql(query, conn) #solo cuenta los registros con 'flag' no los nulos

   COUNT(available_globally)
0                      11115

In [298]:
query = sqla.text("""
  SELECT available_globally, COUNT(id) as 'Conteo'
  FROM movie
  GROUP BY available_globally;
  """)
pd.read_sql(query, conn) #conteo separando si tienen 'flag' o no (nulos)

  available_globally  Conteo
0            b'\x01'    1826
1            b'\x00'    9289
2               None     672

In [299]:
query = sqla.text("""
  SELECT available_globally, COUNT(id) as 'Conteo', (COUNT(id)/(SELECT COUNT(available_globally) FROM movie))*100 as 'Porcentaje'
  FROM movie
  WHERE available_globally = 0
  GROUP BY available_globally;
  """)
pd.read_sql(query, conn) #cuenta los id filtrados por el where (no disponibles en USA), luego divide solo por los registros que tienen 'flag'

  available_globally  Conteo  Porcentaje
0            b'\x00'    9289     83.5717

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?
* ¿Cuántas películas tienen el campo `locale` con valor `NULL`?

In [300]:
query = sqla.text("""
  SELECT locale, COUNT(id) as 'Conteo'
  FROM movie
  GROUP BY locale;
""")
pd.read_sql(query, conn) #solo existe el idioma inglés y 11,255 peliculas no tienen un idioma asignado al registro

  locale  Conteo
0   None   11255
1     en     532

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

In [301]:
query = sqla.text("""
  SELECT locale, COUNT(id) as 'Conteo'
  FROM movie
  WHERE original_title <> title AND locale IS NULL
  GROUP BY locale;
  """)
pd.read_sql(query, conn) #registros en otro idioma original, locale es null. No coincide con el número de null

  locale  Conteo
0   None    3947

In [302]:
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE original_title <> title AND locale IS NULL;
  """)
df = pd.read_sql(query, conn)
df.head(5)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,3,2024-01-01,2024-01-01,b'\x01',None,La sociedad de la nieve,2024-01-04,146,Society of the Snow
1,4,2024-01-01,2024-01-01,b'\x01',None,Sous la Seine,2024-06-05,104,Under Paris
2,17,2024-01-01,2024-01-01,b'\x01',None,황야,2024-01-26,109,Badland Hunters
3,20,2024-01-01,2024-01-01,b'\x01',None,Fabbricante di lacrime,2024-04-04,105,The Tearsmith
4,22,2024-01-01,2024-01-01,b'\x00',None,Avgrunden,2024-02-16,103,The Abyss

In [303]:
query = sqla.text("""
  SELECT locale, COUNT(id) as 'Conteo'
  FROM movie
  WHERE original_title = title AND locale IS NULL
  GROUP BY locale;
  """)
pd.read_sql(query, conn) #registros en otro idioma (español, portugués, etc.) SQL no los reconoce en la query
                         #title y original_title solo tienen una tilde de diferencia, locale es null

  locale  Conteo
0   None      17

In [304]:
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE original_title = title AND locale IS NULL;
  """)
df = pd.read_sql(query, conn)
df.head(5)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,1089,2024-01-01,2024-01-01,b'\x00',None,Recep İvedik 7,None,133,Recep Ivedik 7
1,1349,2024-01-01,2024-01-01,b'\x00',None,Verónica,None,105,Veronica
2,3509,2024-01-01,2024-01-01,b'\x00',None,Fantômas,None,100,Fantomas
3,3611,2024-01-01,2024-01-01,b'\x00',None,Luccas Neto em: O Hotel Mágico,None,70,Luccas Neto em: O Hotel Magico
4,4566,2024-01-01,2024-01-01,b'\x00',None,Un día en el paraíso,None,97,Un Dia En El Paraiso

In [305]:
query = sqla.text("""
  SELECT locale, COUNT(id) as 'Conteo'
  FROM movie
  WHERE title IS NULL AND locale IS NULL
  GROUP BY locale;
  """)
pd.read_sql(query, conn) #registros con locale null y con title null

Empty DataFrame
Columns: [locale, Conteo]
Index: []

In [306]:
query = sqla.text("""
  SELECT locale, COUNT(id) as 'Conteo'
  FROM movie
  WHERE original_title IS NULL AND locale IS NULL
  GROUP BY locale;
  """)
pd.read_sql(query, conn) #registros con locale null y original title null

  locale  Conteo
0   None    7291

In [307]:
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE original_title IS NULL AND locale IS NULL;
  """)
df = pd.read_sql(query, conn)
df.tail(12)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
7279,11758,2024-01-01,2024-01-01,None,None,None,None,124,Dream
7280,11759,2024-01-01,2024-01-01,None,None,None,None,91,No Ritmo da Fé
7281,11762,2024-01-01,2024-01-01,None,None,None,None,133,Kingdom2: Far and Away
7282,11763,2024-01-01,2024-01-01,None,None,None,None,133,Kingdom
7283,11764,2024-01-01,2024-01-01,None,None,None,None,154,Maamannan (Tamil)
7284,11771,2024-01-01,2024-01-01,None,None,None,None,121,Rebound
7285,11775,2024-01-01,2024-01-01,None,None,None,None,121,Afwaah
7286,11776,2024-01-01,2024-01-01,None,None,None,None,94,Faithfully Yours
7287,11779,2024-01-01,2024-01-01,None,None,None,None,85,King of Clones
7288,11780,2024-01-01,2024-01-01,None,None,None,None,112,Black Clover: Sword of the Wizard King
7289,11781,2024-01-01,2024-01-01,None,None,None,None,100,You Do You
7290,11787,2024-01-01,2024-01-01,None,None,None,None,94,Mother's Day

En conclusión, locale = NULL no debería utilizarse como indicador de que una pelicula está en otro idioma. Como se muestra anteriormente, en varios casos aunque locale es NULL, el title es igual al original_title (con la diferencia de que uno contiene tilde). Por último, en la mayoría de casos el locale y el original_title son NULL. Aunque el titulo original de las películas sea distinto al inglés no podemos identificarlas a simple vista. Como tampoco podemos identificar a las películas cuyo titulo original esté en inglés.

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [308]:
query = sqla.text("""
  SELECT movie.id, movie.title, MAX(view_summary.cumulative_weeks_in_top10) as 'Pelicula con mas tiempo en Top10'
  FROM view_summary
  JOIN movie ON view_summary.movie_id = movie.id
  GROUP BY movie.id, movie.title
  HAVING MAX(view_summary.cumulative_weeks_in_top10) = (SELECT MAX(cumulative_weeks_in_top10) FROM view_summary WHERE movie_id IS NOT NULL);
  """)
pd.read_sql(query, conn)

      id                        title  Pelicula con mas tiempo en Top10
0  11197                The Boss Baby                                22
1  11237  The Super Mario Bros. Movie                                22

6.	Identifica los 10 programas de TV con mayor cantidad de temporadas.

In [309]:
query = sqla.text("""
  SELECT tv_show.title, COUNT(season.season_number) AS 'Número de temporadas'
  FROM season
  JOIN tv_show ON season.tv_show_id = tv_show.id
  GROUP BY tv_show.title
  ORDER BY COUNT(season.season_number) DESC
  LIMIT 10;
  """)
pd.read_sql(query, conn)

                               title  Número de temporadas
0         How do you like Wednesday?                    26
1                     Grey's Anatomy                    20
2                   Naruto Shippuden                    20
3                   Heartland (2007)                    17
4  It's Always Sunny in Philadelphia                    16
5                               NCIS                    15
6                Supernatural (2005)                    15
7                      Archer (2009)                    14
8                         Taskmaster                    14
9                   Call the Midwife                    12

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [310]:
query = sqla.text("""
  SELECT DISTINCT start_date, end_date
  FROM view_summary
  WHERE duration = 'SEMI_ANNUALLY';
  """)
pd.read_sql(query, conn)

   start_date    end_date
0  2024-01-01  2024-06-30
1  2023-07-01  2023-12-31

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [311]:
query = sqla.text("""
  SELECT season.season_number, season.title, view_summary.views, view_summary.start_date, view_summary.end_date
  FROM season
  JOIN tv_show ON season.tv_show_id = tv_show.id
  JOIN view_summary ON season.id = view_summary.season_id
  WHERE tv_show.title = "Grey's Anatomy" AND view_summary.duration = "SEMI_ANNUALLY" AND view_summary.start_date = "2024-01-01"
  ORDER BY view_summary.views DESC;
  """)
pd.read_sql(query, conn)

    season_number                      title    views  start_date    end_date
0               1   Grey's Anatomy: Season 1  3600000  2024-01-01  2024-06-30
1               2   Grey's Anatomy: Season 2  3100000  2024-01-01  2024-06-30
2               3   Grey's Anatomy: Season 3  2900000  2024-01-01  2024-06-30
3               5   Grey's Anatomy: Season 5  2900000  2024-01-01  2024-06-30
4               4   Grey's Anatomy: Season 4  2900000  2024-01-01  2024-06-30
5               6   Grey's Anatomy: Season 6  2800000  2024-01-01  2024-06-30
6               7   Grey's Anatomy: Season 7  2700000  2024-01-01  2024-06-30
7               8   Grey's Anatomy: Season 8  2600000  2024-01-01  2024-06-30
8               9   Grey's Anatomy: Season 9  2500000  2024-01-01  2024-06-30
9              10  Grey's Anatomy: Season 10  2400000  2024-01-01  2024-06-30
10             11  Grey's Anatomy: Season 11  2200000  2024-01-01  2024-06-30
11             12  Grey's Anatomy: Season 12  2000000  2024-01-01  2024-06-30
12             13  Grey's Anatomy: Season 13  2000000  2024-01-01  2024-06-30
13             14  Grey's Anatomy: Season 14  2000000  2024-01-01  2024-06-30
14             19  Grey's Anatomy: Season 19  2000000  2024-01-01  2024-06-30
15             15  Grey's Anatomy: Season 15  1900000  2024-01-01  2024-06-30
16             16  Grey's Anatomy: Season 16  1800000  2024-01-01  2024-06-30
17             18  Grey's Anatomy: Season 18  1700000  2024-01-01  2024-06-30
18             17  Grey's Anatomy: Season 17  1700000  2024-01-01  2024-06-30
19             20  Grey's Anatomy: Season 20   100000  2024-01-01  2024-06-30

La primer temporada de Grey's Anatomy es la que presenta mayor cantidad de vistas en el primer semestre de 2024. Las siguientes temporadas mantienen vistas bastante estables. Sin embargo, a medida avanza el número de temporada, las vistas bajan notoriamente, esto podría deberse a que los espectadores pierden interés en la trama. Por último, la temporada 20 es la que menor cantidad de vistas presenta, podemos suponer que se debe a que fue estrenada en el periodo de análisis y no logró captar la atención de los usuarios de Netflix.

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [312]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

In [313]:
#dejo solo las columnas que voy a usar, para facilitarme los pasos siguientes
view_summary = view_summary[['id', 'season_id', 'views', 'start_date', 'end_date']]
view_summary.head(2)

   id  season_id      views  start_date    end_date
0   1        NaN  143800000  2024-01-01  2024-06-30
1   2        NaN  129400000  2024-01-01  2024-06-30

In [314]:
season = season[['id', 'tv_show_id', 'title', 'season_number']]
season.head(2)

   id  tv_show_id                         title  season_number
0   1           1  Fool Me Once: Limited Series            NaN
1   2           2          Bridgerton: Season 3            3.0

In [315]:
tv_show = tv_show[['id', 'title']]
tv_show.head(2)

   id         title
0   1  Fool Me Once
1   2    Bridgerton

In [316]:
merge1 = view_summary.merge(season, on=None, left_on= 'season_id', right_on= 'id')
merge2 = merge1.merge(tv_show, on=None, left_on= 'tv_show_id', right_on= 'id')
df = merge2
df.head(2)

,id_x,season_id,views,start_date,end_date,id_y,tv_show_id,title_x,season_number,id,title_y
0,21114,1.0,107500000,2024-01-01,2024-06-30,1,1,Fool Me Once: Limited Series,NaN,1,Fool Me Once
1,21115,2.0,91900000,2024-01-01,2024-06-30,2,2,Bridgerton: Season 3,3.0,2,Bridgerton

In [317]:
df_greys_anatomy = df[(df['title_y'] == "Grey's Anatomy") & (pd.to_datetime(df['start_date']) == pd.to_datetime("2024-01-01"))].sort_values(by='views', ascending=False)
df_greys_anatomy = df_greys_anatomy[['season_number', 'title_x', 'views', 'start_date', 'end_date']]
df_greys_anatomy

,season_number,title_x,views,start_date,end_date
986,1.0,Grey's Anatomy: Season 1,3600000,2024-01-01,2024-06-30
1188,2.0,Grey's Anatomy: Season 2,3100000,2024-01-01,2024-06-30
1288,3.0,Grey's Anatomy: Season 3,2900000,2024-01-01,2024-06-30
1290,5.0,Grey's Anatomy: Season 5,2900000,2024-01-01,2024-06-30
1301,4.0,Grey's Anatomy: Season 4,2900000,2024-01-01,2024-06-30
1352,6.0,Grey's Anatomy: Season 6,2800000,2024-01-01,2024-06-30
1428,7.0,Grey's Anatomy: Season 7,2700000,2024-01-01,2024-06-30
1486,8.0,Grey's Anatomy: Season 8,2600000,2024-01-01,2024-06-30
1545,9.0,Grey's Anatomy: Season 9,2500000,2024-01-01,2024-06-30
1605,10.0,Grey's Anatomy: Season 10,2400000,2024-01-01,2024-06-30
1787,11.0,Grey's Anatomy: Season 11,2200000,2024-01-01,2024-06-30
2011,12.0,Grey's Anatomy: Season 12,2000000,2024-01-01,2024-06-30
2015,13.0,Grey's Anatomy: Season 13,2000000,2024-01-01,2024-06-30
2017,14.0,Grey's Anatomy: Season 14,2000000,2024-01-01,2024-06-30
2025,19.0,Grey's Anatomy: Season 19,2000000,2024-01-01,2024-06-30
2123,15.0,Grey's Anatomy: Season 15,1900000,2024-01-01,2024-06-30
2250,16.0,Grey's Anatomy: Season 16,1800000,2024-01-01,2024-06-30
2366,18.0,Grey's Anatomy: Season 18,1700000,2024-01-01,2024-06-30
2377,17.0,Grey's Anatomy: Season 17,1700000,2024-01-01,2024-06-30
10015,20.0,Grey's Anatomy: Season 20,100000,2024-01-01,2024-06-30

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [318]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [319]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [320]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/content/drive/MyDrive/Colab Notebooks/Ciencia y Analitica de Datos/Tareas/Semana3"
os.chdir(DIR)

In [325]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [326]:
#usando las indicaciones de la pagina web: firebase.google.com
#(https://firebase.google.com/docs/firestore/quickstart#python_3)
employees_ref = db.collection("EMPLOYEE")
docs = employees_ref.get()
#en la pagina aparece un loop "for", pero ese me dio error, así que lo complementé con las siguientes líneas

ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f5216b33890>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_plugin_wrapping.py", line 106, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/auth/transport/grpc.py", line 81, in _get_authorization_headers
    self._credentials.before_request(
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 270, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.12/dist-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})

RetryError: Timeout of 300.0s exceeded, last exception: 503 Getting metadata from plugin failed with error: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})

In [ ]:
#usando las indicaciones del usuario Divyani Yadav (2022),
#foro de stackoverflow (https://stackoverflow.com/questions/71598928/importing-data-from-firestore-to-python)
employees_ref = db.collection("EMPLOYEE")
docs = employees_ref.get()
empleados = list(map(lambda x: {**x.to_dict(), 'id': x.id}, docs))
df_empleados = pd.DataFrame(empleados)
df_empleados.set_index('id', inplace=True)

In [ ]:
df_empleados

In [323]:
firebase_admin.delete_app(firebase_admin.get_app())